### ISSUE TITLE
framing of "open source organization"

### ISSUE THREAD

**Issue by robbiemorrison** [pypsa-meets-africa/pypsa-meets-africa.github.io#1]
The landing page used the phrase "Initiate a stable open source organization".

The concept of an open source organization is somewhat vague and the following phrasing might be better:

- Initiate a stable open source support organization
- Initiate a stable support organization

Just a suggestion, HTH, R

**Comment by pz-max** [comment]
Great thanks for that comment Robbie! We added your recommendation.
Next time you can submit a pull request and be listed as a collaborator here :+1:
