### ISSUE TITLE
project now listed on wikipedia

### ISSUE THREAD

**Issue by robbiemorrison** [pypsa-meets-africa/pypsa-meets-africa.github.io#2]
The project is now listed on wikipedia:

- https://en.wikipedia.org/w/index.php?title=Open_energy_system_models&type=revision&diff=1037535568&oldid=1031448791
- https://en.wikipedia.org/wiki/Open_energy_system_models#PyPSA

Feel free to edit that text.

**Comment by pz-max** [comment]
Super cool :100: ! Thank you Robbie

**Comment by robbiemorrison** [comment]
Resolved.
